### ISSUE TITLE
Introduce CRITICAL state for thresholds 

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#22]
Currently only WARNING is supported for thresholds of suites/tests/keywords. 
Also introduce CRITICAL. 

(Who ever uses this: bear in mind to use this with caution. When you generate SLA reports in CheckMK, you'll throw together the Critical states of application outages with Critical states generated by too long runtimes (even if the application worked in the end).

**Comment by mike1098** [comment]
Much appreciate the critical thresholds. This is needed to have different levels of escalation. As long as the plugin provides a clear and meaningful output there should be no confusion. Following the robotframework documentation a test should never run in to a timeout because then the robot process will kill the test and may leave the environment in an unstable condition.

**Comment by simonmeggle** [comment]
You should always define [suite teardown keywords](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-setup-and-teardown) to ensure that Robot leaves a clean environment if a timeout has occured. 
Keywords defined in Suite Teardown are not affected by the timeout and get executed in any case.
